# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_humans', '0005_userevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='event_type',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
