# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-01-26 00:19
from __future__ import unicode_literals

from django.db import migrations

DROP_UNUSED_TABLES = """\
    DROP TABLE IF EXISTS illumina_uyg_userdata;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('open_humans', '0007_blogpost'),
    ]

    operations = [
        migrations.RunSQL(DROP_UNUSED_TABLES),
    ]
