# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-06-11 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import open_humans.models
import open_humans.storage


class Migration(migrations.Migration):

    dependencies = [
        ('open_humans', '0009_grantproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantproject',
            name='photo',
            field=models.ImageField(blank=True, max_length=1024, storage=open_humans.storage.PublicStorage(), upload_to=open_humans.models.get_grant_project_image_upload_path),
        ),
    ]
