# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-03-14 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_humans', '0009_grantproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantproject',
            name='grant_date',
            field=models.DateTimeField(null=True),
        ),
    ]
