# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-03-14 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_humans', '0010_grantproject_grant_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantproject',
            name='grant_date',
            field=models.DateField(null=True),
        ),
    ]
