# Generated by Django 2.0.7 on 2018-08-30 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_humans', '0012_auto_20180725_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='badges',
        ),
    ]
