# Generated by Django 2.1.1 on 2018-09-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_humans', '0013_remove_member_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password_reset_redirect',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
