# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-06-13 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twenty_three_and_me', '0001_squashed_0008_auto_20160209_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
