# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 23:13
from __future__ import unicode_literals

import activities.data_selfie.models
import common.fields
import data_import.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_import', '0007_auto_20160111_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=1024, upload_to=data_import.models.get_upload_path)),
                ('metadata', jsonfield.fields.JSONField(default={})),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datafile_data_selfie', to='data_import.DataRetrievalTask')),
            ],
            options={
                'verbose_name': 'data selfie data file',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genome_file', models.FileField(max_length=1024, null=True, upload_to=activities.data_selfie.models.get_upload_path)),
                ('user', common.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_selfie', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'data selfie user data',
                'verbose_name_plural': 'data selfie user data',
            },
        ),
        migrations.AddField(
            model_name='datafile',
            name='user_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_selfie.UserData'),
        ),
    ]
