# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-01 23:12
from __future__ import unicode_literals

import common.fields
import data_import.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_import', '0001_squashed_0020_auto_20160729_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=1024, upload_to=data_import.utils.get_upload_path)),
                ('metadata', jsonfield.fields.JSONField(default={})),
            ],
            options={
                'verbose_name': 'data selfie data file',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', common.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_selfie', to=settings.AUTH_USER_MODEL)),
                ('seen_page', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'data selfie user data',
                'verbose_name_plural': 'data selfie user data',
            },
        ),
        migrations.AddField(
            model_name='datafile',
            name='user_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_selfie.UserData'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='user_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='id',
            field=models.IntegerField(verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='parent',
            field=models.IntegerField(default=-1, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datafile',
            name='parent',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='parent_data_selfie', serialize=False, to='data_import.DataFile'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='metadata',
        ),
        migrations.RenameModel(
            old_name='DataFile',
            new_name='DataSelfieDataFile',
        ),
        migrations.AlterModelOptions(
            name='dataselfiedatafile',
            options={},
        ),
        migrations.RemoveField(
            model_name='dataselfiedatafile',
            name='user_data',
        ),
    ]
