# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_selfie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='user_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
