# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-04-14 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_selfie', '0001_squashed_0008_auto_20160427_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataselfiedatafile',
            name='parent',
        ),
        migrations.DeleteModel(
            name='DataSelfieDataFile',
        ),
    ]
