# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_selfie', '0002_datafile_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='seen_page',
            field=models.BooleanField(default=False),
        ),
    ]
