# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_selfie', '0004_auto_20160209_0559'),
    ]

    operations = [
        # then change parent field to an actual primary key/OneToOneField
        migrations.AlterField(
            model_name='datafile',
            name='parent',
            field=models.OneToOneField(
                default=-1,
                on_delete=models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name='parent_data_selfie',
                serialize=False,
                to='data_import.DataFile'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='metadata',
        ),
    ]
