# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0013_auto_20160209_0559'),
        ('data_selfie', '0005_auto_20160209_2109'),
    ]

    operations = [
        migrations.RenameModel('DataFile', 'DataSelfieDataFile'),
    ]
