# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_selfie', '0006_auto_20160209_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataselfiedatafile',
            options={},
        ),
        migrations.RemoveField(
            model_name='dataselfiedatafile',
            name='user_data',
        ),
    ]
