# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 12:56
from __future__ import unicode_literals

from django.db import migrations


def migrate_remove_bad_files(apps, schema_editor):
    DataFile = apps.get_model('data_import', 'DataFile')
    DataSelfieDataFile = apps.get_model('data_selfie', 'DataSelfieDataFile')

    for data_file in DataFile.objects.filter(source='data_selfie'):
        try:
            DataSelfieDataFile.objects.get(parent_id=data_file.id)
        except DataSelfieDataFile.DoesNotExist:
            print 'removing bad DataFile with ID {}'.format(data_file.id)

            data_file.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0001_squashed_0020_auto_20160729_1632'),
        ('data_selfie', '0007_auto_20160209_2131'),
    ]

    operations = [
        migrations.RunPython(migrate_remove_bad_files),
    ]
