from collections import OrderedDict
from datetime import datetime
import os

from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.db import models


def get_upload_dir(datafile_model, user):
    """
    Construct the upload dir path for a given User and DataFile model.
    """
    return "member/%s/imported-data/%s/" % (user.username,
                                            datafile_model._meta.app_label)

def get_upload_path(instance, filename=''):
    """
    Construct the upload path for a given DataFile and filename.
    """
    return "%s%s" % (get_upload_dir(type(instance),
                                    instance.user_data.user),
                     filename)

class DataRetrievalTask(models.Model):
    """
    Model for tracking DataFile import requests.

    The datafile_model field stores a ContentType referring to the app-specific
    DataFile model appropriate for files (if any) generated by the task.

    A DataRetrievalTask is related to DataFile models as a ForeignKey.
    """
    TASK_SUCCESSFUL = 0  # Celery task complete, successful.
    TASK_SUBMITTED = 1   # Sent to Open Humans Data Processing.
    TASK_FAILED = 2      # Celery task complete, failed.
    TASK_QUEUED = 3      # OH Data Processing has sent to broker.
    TASK_INITIATED = 4   # Celery has received and started the task.
    TASK_POSTPONED = 5   # Task not submitted yet (eg pending email validation)

    TASK_STATUS_CHOICES = OrderedDict(
        [(TASK_SUCCESSFUL, 'Completed successfully'),
         (TASK_SUBMITTED, 'Submitted'),
         (TASK_FAILED, 'Failed'),
         (TASK_QUEUED, 'Queued'),
         (TASK_INITIATED, 'Initiated'),
         (TASK_POSTPONED, 'Postponed')])

    status = models.IntegerField(choices=TASK_STATUS_CHOICES.items(),
                                 default=TASK_SUBMITTED)
    start_time = models.DateTimeField(default=datetime.now)
    complete_time = models.DateTimeField(null=True)
    datafile_model = models.ForeignKey(ContentType)
    user = models.ForeignKey(User)

    def __unicode__(self):
        return '%s:%s:%s' % (self.user,
                             self.source,
                             self.TASK_STATUS_CHOICES[self.status])

    @property
    def source(self):
        return self.datafile_model.model_class()._meta.app_label


class BaseDataFile(models.Model):
    """
    The 'user_data' field must be defined, and must be a model which
    itself has a 'user' field that is a OneToOneField to User.
    """
    file = models.FileField(upload_to=get_upload_path)
    task = models.ForeignKey(DataRetrievalTask)
    user_data = None

    class Meta:
        abstract = True

    def __unicode__(self):
        return '%s:%s:%s' % (self.user_data.user,
                             self.source,
                             self.file)

    @property
    def source(self):
        return self._meta.app_label

    @property
    def basename(self):
        return os.path.basename(self.file.name)
