from time import time


def get_upload_path(instance, filename):
    """
    Construct the upload path for a upload-based data source.
    """
    return '{0}{1}'.format(
        get_upload_dir(source=instance, user=instance.user), filename)


def get_upload_dir(source, user):
    """
    Construct the upload directory for a upload-based data source.

    e.g. 23andMe uploaded files. These uploads are the original uploads from
    participants. With the exception of Data Selfie files, these will be
    processed and will not themselves be DataFiles (i.e. not intended to be
    shared or managed by participants).
    """
    return 'member/{0}/uploaded-data/{1}/{2}/'.format(
        user.id, source._meta.app_label, int(time()))


def get_upload_dir_validator(source, user):
    """
    Return regexp string that should match a path generated by get_upload_dir.
    """
    return r'^member/{0}/uploaded-data/{1}/\d+/'.format(
        user.id, source._meta.app_label)
