# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 21:28
from __future__ import unicode_literals

import common.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_import', '0001_squashed_0020_auto_20160729_1632'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UBiomeSample',
            fields=[
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='parent_ubiome', serialize=False, to='data_import.DataFile')),
                ('sample_type', models.IntegerField(choices=[(0, b'Gut'), (1, b'Mouth'), (2, b'Nose'), (3, b'Skin'), (4, b'Genitals'), (5, b'Other')])),
                ('sample_date', models.DateField(blank=True, help_text=b'Format: month/day/year, e.g. 10/23/2015', null=True)),
                ('taxonomy', models.TextField(help_text=b'Click "Download taxonomy" on uBiome. Copy all of it and paste it here.')),
                ('additional_notes', models.TextField(blank=True, help_text=b'Any additional notes, if you would like to add them.')),
            ],
            bases=('data_import.datafile',),
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', common.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubiome', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'uBiome user data',
                'verbose_name_plural': 'uBiome user data',
            },
        ),
    ]
