# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-01 23:26
from __future__ import unicode_literals

import common.fields
import data_import.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_import', '0001_squashed_0020_auto_20160729_1632'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', common.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubiome', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'uBiome user data',
                'verbose_name_plural': 'uBiome user data',
            },
        ),
        migrations.CreateModel(
            name='UBiomeSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_file', models.FileField(max_length=1024, upload_to=data_import.utils.get_upload_path)),
                ('taxonomy', models.TextField(help_text=b'Click "Download taxonomy" on uBiome. Copy all of it and paste it here.')),
                ('additional_notes', models.TextField(blank=True, help_text=b'Any additional notes, if you would like to add them.')),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubiome.UserData')),
            ],
        ),
    ]
