# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0001_squashed_0020_auto_20160729_1632'),
        ('ubiome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubiomesample',
            name='parent',
        ),
        migrations.DeleteModel(
            name='UBiomeSample',
        ),
    ]
