# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-06-13 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubiome', '0001_squashed_0005_auto_20160614_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubiomesample',
            name='user_data',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='user',
        ),
        migrations.DeleteModel(
            name='UBiomeSample',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
