# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 10:26
from __future__ import unicode_literals

import data_import.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubiome', '0002_auto_20160310_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='UBiomeSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_file', models.FileField(max_length=1024, upload_to=data_import.utils.get_upload_path)),
                ('sample_type', models.IntegerField(choices=[(0, b'Gut'), (1, b'Mouth'), (2, b'Nose'), (3, b'Skin'), (4, b'Genitals'), (5, b'Other')])),
                ('sample_date', models.DateField(blank=True, help_text=b'Format: month/day/year, e.g. 10/23/2015', null=True)),
                ('taxonomy', models.TextField(help_text=b'Click "Download taxonomy" on uBiome. Copy all of it and paste it here.')),
                ('additional_notes', models.TextField(blank=True, help_text=b'Any additional notes, if you would like to add them.')),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubiome.UserData')),
            ],
        ),
    ]
