# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 16:18
from __future__ import unicode_literals

from datetime import datetime

from django.db import migrations


def set_archive_field(apps, *args):
    DataFile = apps.get_model('data_import', 'DataFile')

    now = datetime.now()

    DataFile.objects.filter(is_latest=False).update(archived=now)


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0003_datafile_archived'),
    ]

    operations = [
        migrations.RunPython(set_archive_field),
    ]
