# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0006_testdatafile_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataretrievaltask',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
