# Generated by Django 2.1.4 on 2018-12-28 19:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0007_auto_20180813_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFileKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='datafile',
            name='key',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_import.DataFileKey'),
        ),
    ]
