# Generated by Django 2.0.7 on 2018-08-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0007_auto_20180813_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemovedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('member_id', models.CharField(max_length=32)),
                ('file_url', models.CharField(max_length=1024)),
                ('source', models.CharField(max_length=32)),
            ],
        ),
    ]
