# Generated by Django 2.1.4 on 2019-01-03 18:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0008_datafilekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafilekey',
            name='access_token',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='datafilekey',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='datafilekey',
            name='project_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='newdatafileaccesslog',
            name='data_file_key',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
