# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0008_auto_20160209_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datafiles', to='data_import.DataRetrievalTask'),
        ),
    ]
