# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 04:20
from __future__ import unicode_literals

from django.db import migrations

APPS = [
    'american_gut',
    'data_selfie',
    'go_viral',
    'pgp',
    'runkeeper',
    'twenty_three_and_me',
    'wildlife',
]

def migrate_data_files(apps, schema_editor):
    print

    for app in APPS:
        DataFile = apps.get_model('data_import', 'DataFile')
        OldDataFile = apps.get_model(app, 'DataFile')

        for old_data_file in OldDataFile.objects.all():
            data_file = DataFile()

            data_file.file = old_data_file.file
            data_file.metadata = old_data_file.metadata
            data_file.user = old_data_file.user_data.user
            data_file.source = old_data_file._meta.app_label

            if hasattr(old_data_file, 'task'):
                data_file.task = old_data_file.task

            data_file.save()

        print 'finished with {}'.format(app)


class Migration(migrations.Migration):

    dependencies = [
        ('american_gut', '0009_auto_20160206_0417'),
        ('data_import', '0009_null_task_id'),
        ('data_selfie', '0003_userdata_seen_page'),
        ('go_viral', '0008_auto_20160206_0442'),
        ('pgp', '0006_datafile_metadata'),
        ('runkeeper', '0007_datafile_metadata'),
        ('twenty_three_and_me', '0007_datafile_metadata'),
        ('wildlife', '0004_datafile_metadata'),
    ]

    operations = [
        migrations.RunPython(migrate_data_files),
    ]
