# Generated by Django 2.1.4 on 2019-01-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0010_custom_20190107_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafilekey',
            name='datafile_id',
            field=models.IntegerField(),
        ),
    ]
