# Generated by Django 2.1.3 on 2019-03-12 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("data_import", "0011_auto_20190107_1907")]

    operations = [
        migrations.AlterField(
            model_name="newdatafileaccesslog",
            name="data_file",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="access_logs",
                to="data_import.DataFile",
            ),
        ),
        migrations.AlterField(
            model_name="newdatafileaccesslog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
