# Generated by Django 2.1.3 on 2019-03-07 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("data_import", "0012_datatype")]

    operations = [
        migrations.AlterField(
            model_name="datatype",
            name="name",
            field=models.CharField(
                max_length=128,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[\\w\\-\\s]+$",
                        "Only alphanumeric characters, space, dash, and underscore are allowed.",
                    )
                ],
            ),
        )
    ]
