# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0012_remove_dataretrievaltask_datafile_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafileaccesslog',
            name='data_file_model',
        ),
        migrations.RemoveField(
            model_name='datafileaccesslog',
            name='user',
        ),
        migrations.DeleteModel(
            name='DataFileAccessLog',
        ),
    ]
