# Generated by Django 2.1.7 on 2019-03-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("data_import", "0013_auto_20190326_1840")]

    operations = [
        migrations.AlterField(
            model_name="newdatafileaccesslog",
            name="aws_url",
            field=models.CharField(max_length=400, null=True),
        )
    ]
