# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 22:34
from __future__ import unicode_literals
from collections import defaultdict

from django.db import migrations, models


def migrate_is_latest(apps, schema_editor):
    DataFile = apps.get_model('data_import', 'DataFile')

    # set all DataFiles to not be the latest
    DataFile.objects.update(is_latest=False)

    # set the latest DataFiles to be the latest
    data_files = DataFile.objects.order_by('user__username',
                                           '-task__start_time')

    tasks = defaultdict(dict)

    for data_file in data_files:
        if data_file.user_id not in tasks[data_file.source]:
            tasks[data_file.source][data_file.user_id] = data_file.task_id

        if tasks[data_file.source][data_file.user_id] != data_file.task_id:
            continue

        data_file.is_latest = True
        data_file.save()


class Migration(migrations.Migration):

    dependencies = [
        ('public_data', '0009_auto_20150325_1731'),
        ('data_import', '0013_auto_20160209_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='is_latest',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(migrate_is_latest),
    ]
