# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 01:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


def migrate_created(apps, schema_editor):
    DataFile = apps.get_model('data_import', 'DataFile')

    for data_file in DataFile.objects.all():
        data_file.created = data_file.task.start_time
        data_file.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0014_datafile_is_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 12, 1, 55, 2, 251836, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_created),
    ]
