# Generated by Django 2.1.3 on 2019-03-27 19:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("data_import", "0014_auto_20190327_0035")]

    operations = [
        migrations.AddField(
            model_name="awsdatafileaccesslog",
            name="serialized_data_file",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="newdatafileaccesslog",
            name="serialized_data_file",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, null=True
            ),
        ),
    ]
