# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 07:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0015_datafile_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
