# Generated by Django 2.1.3 on 2019-03-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("data_import", "0015_auto_20190327_1956")]

    operations = [
        migrations.RemoveField(model_name="awsdatafileaccesslog", name="data_file")
    ]
