# Generated by Django 2.1.7 on 2019-03-28 23:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("data_import", "0016_remove_awsdatafileaccesslog_data_file")]

    operations = [
        migrations.CreateModel(
            name="DataType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[\\w\\-\\s]+$",
                                "Only alphanumeric characters, space, dash, and underscore are allowed.",
                            )
                        ],
                    ),
                ),
                ("description", models.CharField(max_length=512)),
                ("created", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="data_import.DataType",
                    ),
                ),
            ],
        )
    ]
