# Generated by Django 2.1.3 on 2019-03-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("data_import", "0016_remove_awsdatafileaccesslog_data_file")]

    operations = [
        migrations.AlterField(
            model_name="awsdatafileaccesslog",
            name="bucket_key",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="awsdatafileaccesslog",
            name="referrer",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="awsdatafileaccesslog",
            name="request_uri",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="datafilekey",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
