# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0016_auto_20160212_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdatafileaccesslog',
            name='data_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='data_import.DataFile'),
        ),
    ]
