# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0017_auto_20160229_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datafiles', to='data_import.DataRetrievalTask'),
        ),
    ]
