# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0019_auto_20160727_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataretrievaltask',
            name='user',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='task',
        ),
        migrations.DeleteModel(
            name='DataRetrievalTask',
        ),
    ]
