# Generated by Django 2.2 on 2019-04-30 17:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("data_import", "0019_datatype")]

    operations = [
        migrations.AlterField(
            model_name="datatype",
            name="history",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, editable=False
            ),
        )
    ]
