# Generated by Django 2.2.1 on 2019-05-21 20:31

import data_import.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("data_import", "0020_auto_20190430_1756")]

    operations = [
        migrations.AlterField(
            model_name="datafile",
            name="file",
            field=models.FileField(
                max_length=1024,
                unique=True,
                upload_to=data_import.utils.get_upload_path,
            ),
        )
    ]
