# Generated by Django 2.2.3 on 2019-11-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("data_import", "0021_auto_20190521_2031")]

    operations = [
        migrations.AddField(
            model_name="datatype", name="details", field=models.TextField(blank=True)
        ),
        migrations.AddField(
            model_name="datatype",
            name="uploadable",
            field=models.BooleanField(default=False),
        ),
    ]
