# Generated by Django 2.2.13 on 2020-12-22 19:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("data_import", "0024_auto_20201222_1757")]

    operations = [
        migrations.RemoveField(model_name="datafilekey", name="id"),
        migrations.AlterField(
            model_name="datafilekey",
            name="key",
            field=models.CharField(
                default=uuid.uuid4,
                max_length=36,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
