# Generated by Django 2.2.1 on 2019-05-08 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("private_sharing", "0022_auto_20190507_1843"),
        ("public_data", "0002_auto_20171213_1947"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicdataaccess",
            name="project_membership",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="private_sharing.DataRequestProjectMember",
            ),
        ),
        migrations.AlterField(
            model_name="publicdataaccess",
            name="data_source",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
