# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_data', '0003_publicdataaccess_updates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicdatafileaccess',
            name='data_file_model',
        ),
        migrations.DeleteModel(
            name='PublicDataFileAccess',
        ),
    ]
