# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 06:47
from __future__ import unicode_literals

import common.fields
import common.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', common.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitbit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fitbit user data',
                'verbose_name_plural': 'Fitbit user data',
            },
            bases=(models.Model, common.mixins.UserSocialAuthUserData),
        ),
    ]
