# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcf_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcfdata',
            name='vcf_source',
            field=models.CharField(choices=[(b'', b'--------'), (b'dna_land', b'DNALand Genome Imputation'), (b'full_genomes_corp', b'Full Genomes Corp.'), (b'genes_for_good', b'Genes For Good'), (b'genos_exome', b'Genos'), (b'illumina_uyg', b'Illumina Understand Your Genome'), (b'twenty_three_and_me', b'23andMe Exome Pilot'), (b'veritas_genetics', b'Veritas Genetics'), (b'other', b'Other')], default=b'', max_length=30),
        ),
    ]
