# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-06-13 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcf_data', '0003_remove_userdata_genome_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vcfdata',
            name='user_data',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
        migrations.DeleteModel(
            name='VCFData',
        ),
    ]
