# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 04:17
from __future__ import unicode_literals

import json

from django.db import migrations


def migrate_data(apps, schema_editor):
    Barcode = apps.get_model('american_gut', 'Barcode')

    for barcode in Barcode.objects.all():
        user_data = barcode.user_data

        if isinstance(user_data.data, basestring):
            user_data.data = json.loads(user_data.data)

        if 'barcodes' not in user_data.data:
            user_data.data['barcodes'] = []

        user_data.data['barcodes'].append(barcode.value)
        user_data.save()


class Migration(migrations.Migration):

    dependencies = [
        ('american_gut', '0008_datafile_metadata'),
    ]

    operations = [
        migrations.RunPython(migrate_data),
        migrations.RemoveField(
            model_name='barcode',
            name='user_data',
        ),
        migrations.DeleteModel(
            name='Barcode',
        ),
    ]
