# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-01 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgp', '0001_squashed_0009_auto_20160212_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huid',
            old_name='value',
            new_name='id',
        ),
    ]
