# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-06-14 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgp', '0002_auto_20160801_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huid',
            name='user_data',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='user',
        ),
        migrations.DeleteModel(
            name='HuId',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
