# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 19:58
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('open_humans', '0003_auto_20151223_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRequestActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_study', models.BooleanField(verbose_name='Is this activity an IRB-approved study?')),
                ('name', models.CharField(max_length=100, verbose_name='Activity or study name')),
                ('leader', models.CharField(max_length=100, verbose_name='Activity leader(s) or principal investigator(s)')),
                ('organization', models.CharField(max_length=100, verbose_name='Organization or institution')),
                ('contact_email', models.EmailField(max_length=254)),
                ('info_url', models.URLField(verbose_name='URL for general information about your activity or study')),
                ('short_description', models.CharField(max_length=140, verbose_name='A short description')),
                ('long_description', models.TextField(max_length=1000, verbose_name='A long description')),
                ('active', models.BooleanField(verbose_name='Whether the activity is currently active')),
                ('request_sources_access', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None, verbose_name="Data sources you're requesting access to")),
                ('request_message_permission', models.BooleanField(verbose_name='Are you requesting permission to message users?')),
                ('request_username_access', models.BooleanField(verbose_name='Are you requesting Open Humans usernames?')),
                ('approved', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('api_access_secret', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DataRequestActivityMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_code', models.CharField(max_length=16)),
                ('message_permission', models.BooleanField()),
                ('username_shared', models.BooleanField()),
                ('sources_shared', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='OAuth2DataRequestActivity',
            fields=[
                ('datarequestactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='private_sharing.DataRequestActivity')),
                ('enrollment_text', models.TextField()),
                ('redirect_url', models.URLField(verbose_name='Redirect URL')),
            ],
            bases=('private_sharing.datarequestactivity',),
        ),
        migrations.CreateModel(
            name='OnSiteDataRequestActivity',
            fields=[
                ('datarequestactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='private_sharing.DataRequestActivity')),
                ('consent_text', models.TextField()),
                ('post_sharing_url', models.URLField()),
            ],
            bases=('private_sharing.datarequestactivity',),
        ),
        migrations.AddField(
            model_name='datarequestactivitymember',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='private_sharing.DataRequestActivity'),
        ),
        migrations.AddField(
            model_name='datarequestactivitymember',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='open_humans.Member'),
        ),
        migrations.AddField(
            model_name='datarequestactivity',
            name='coordinator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='open_humans.Member'),
        ),
    ]
