# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-01 23:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('private_sharing', '0001_squashed_0034_auto_20160727_2138'),
        ('data_import', '0001_squashed_0020_auto_20160729_1632'),
    ]

    operations = [

        migrations.CreateModel(
            name='ProjectDataFile',
            fields=[
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='parent_project_data_file', serialize=False, to='data_import.DataFile')),
                ('direct_sharing_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private_sharing.DataRequestProject')),
            ],
            bases=('data_import.datafile',),
        ),
    ]
