# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauth2datarequestactivity',
            name='enrollment_text',
        ),
        migrations.AddField(
            model_name='oauth2datarequestactivity',
            name='enrollment_url',
            field=models.URLField(default='', help_text="The URL we direct members to if they're interested in sharing data with your study or activity.", verbose_name='Enrollment URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datarequestactivity',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], help_text='If your activity is not active, it won\'t show up in\nlistings, and new data sharing authorizations cannot occur. "Active" status is\nrequired to test authorization processes. Activities which are "active" but not\napproved may have some information shared in an "In Development" section,\nenabling Open Humans members to comment on upcoming studies.', verbose_name='Is the activity is currently active?'),
        ),
        migrations.AlterField(
            model_name='datarequestactivity',
            name='is_study',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Is this activity an IRB-approved study?'),
        ),
        migrations.AlterField(
            model_name='datarequestactivity',
            name='request_message_permission',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Are you requesting permission to message users?'),
        ),
        migrations.AlterField(
            model_name='datarequestactivity',
            name='request_username_access',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Are you requesting Open Humans usernames?'),
        ),
        migrations.AlterField(
            model_name='oauth2datarequestactivity',
            name='redirect_url',
            field=models.URLField(help_text='The return URL for our "authorization code" OAuth2 grant process. You can <a target="_blank" href="">read more about OAuth2 "authorization code" transactions here</a>.', verbose_name='Redirect URL'),
        ),
    ]
