# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 01:16
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0002_auto_20160223_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequestactivity',
            name='request_message_permission',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], help_text='Permission to send messages to the member. This does not grant access to their email address.', verbose_name='Are you requesting permission to message users?'),
        ),
        migrations.AlterField(
            model_name='datarequestactivity',
            name='request_sources_access',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), help_text='List of sources this activity or study is requesting access to on Open Humans.', size=None, verbose_name="Data sources you're requesting access to"),
        ),
        migrations.AlterField(
            model_name='datarequestactivity',
            name='request_username_access',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], help_text="Access to the member's username. This implicitly enables access to anything the user is publicly sharing on Open Humans. Note that this is potentially sensitive and/or identifying.", verbose_name='Are you requesting Open Humans usernames?'),
        ),
        migrations.AlterField(
            model_name='onsitedatarequestactivity',
            name='consent_text',
            field=models.TextField(help_text='The "informed consent" text that describes your activity to Open Humans members.'),
        ),
        migrations.AlterField(
            model_name='onsitedatarequestactivity',
            name='post_sharing_url',
            field=models.URLField(help_text='If provided, after authorizing sharing the\nmember will be taken to this URL. If this URL includes "OH_USER_ID_CODE" within\nit, we will replace that with the member\'s activity-specific user_id_code. This\nallows you to direct them to an external survey you operate (e.g. using Google\nForms) where a pre-filled user_id_code field allows you to connect those\nresponses to corresponding data in Open Humans.', verbose_name='Post-sharing URL'),
        ),
    ]
