# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 21:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ('private_sharing', '0003_auto_20160224_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2datarequestactivity',
            name='application',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datarequestactivity',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], help_text='If your activity is not active, it won\'t show up in\nlistings, and new data sharing authorizations cannot occur. "Active" status is\nrequired to test authorization processes. Activities which are "active" but not\napproved may have some information shared in an "In Development" section,\nenabling Open Humans members to comment on upcoming studies.', verbose_name='Is the activity currently active?'),
        ),
    ]
