# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-26 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0003_auto_20160909_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdatafile',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
