# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0004_auto_20160224_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datarequestactivity',
            options={'verbose_name_plural': 'Data request activities'},
        ),
        migrations.AlterModelOptions(
            name='oauth2datarequestactivity',
            options={'verbose_name': 'OAuth2 data request activity', 'verbose_name_plural': 'OAuth2 data request activities'},
        ),
        migrations.AlterModelOptions(
            name='onsitedatarequestactivity',
            options={'verbose_name': 'On-site data request activity', 'verbose_name_plural': 'On-site data request activities'},
        ),
        migrations.AlterField(
            model_name='datarequestactivity',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
