# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import open_humans.storage
import private_sharing.models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0005_auto_20160224_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequestactivity',
            name='badge_image',
            field=models.ImageField(blank=True, help_text="A badge that will be displayed on the user's profile once they've connected your activity.", max_length=1024, storage=open_humans.storage.PublicStorage(), upload_to=private_sharing.models.badge_upload_path),
        ),
    ]
