# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0006_datarequestactivity_badge_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequestactivity',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='"Active" status is required to perform authorization\nprocesses, including during drafting stage. If a project is not active,\nit won\'t show up in listings, and new data sharing authorizations cannot occur.\nProjects which are "active" but not approved may have some information shared\nin an "In Development" section, so Open Humans members can see potential\nupcoming studies.'),
        ),
        migrations.AlterField(
            model_name='datarequestactivity',
            name='contact_email',
            field=models.EmailField(max_length=254, verbose_name='Contact email for your study or activity'),
        ),
        migrations.AlterField(
            model_name='datarequestactivity',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='open_humans.Member'),
        ),
        migrations.AlterField(
            model_name='datarequestactivity',
            name='is_study',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], help_text='A "study" is doing human subjects research and must have Institutional Review Board approval or equivalent ethics board oversight. Activities can be anything else, e.g. data visualizations.', verbose_name='Is this project a study?'),
        ),
        migrations.AlterField(
            model_name='datarequestactivity',
            name='leader',
            field=models.CharField(max_length=100, verbose_name='Leader(s) or principal investigator(s)'),
        ),
        migrations.AlterField(
            model_name='onsitedatarequestactivity',
            name='post_sharing_url',
            field=models.URLField(help_text='If provided, after authorizing sharing the\nmember will be taken to this URL. If this URL includes "OH_USER_ID_CODE" within\nit, we will replace that with the member\'s project-specific user_id_code. This\nallows you to direct them to an external survey you operate (e.g. using Google\nForms) where a pre-filled user_id_code field allows you to connect those\nresponses to corresponding data in Open Humans.', verbose_name='Post-sharing URL'),
        ),
    ]
