# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 19:29
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import open_humans.storage
import private_sharing.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ('open_humans', '0004_member_badges'),
        ('private_sharing', '0007_auto_20160225_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRequestProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_study', models.BooleanField(choices=[(True, 'Study'), (False, 'Activity')], help_text='A "study" is doing human subjects research and must have Institutional Review Board approval or equivalent ethics board oversight. Activities can be anything else, e.g. data visualizations.', verbose_name='Is this project a study or an activity?')),
                ('name', models.CharField(max_length=100, verbose_name='Project name')),
                ('leader', models.CharField(max_length=100, verbose_name='Leader(s) or principal investigator(s)')),
                ('organization', models.CharField(max_length=100, verbose_name='Organization or institution')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Contact email for your project')),
                ('info_url', models.URLField(verbose_name='URL for general information about your project')),
                ('short_description', models.CharField(max_length=140, verbose_name='A short description')),
                ('long_description', models.TextField(max_length=1000, verbose_name='A long description')),
                ('active', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='"Active" status is required to perform authorization\nprocesses, including during drafting stage. If a project is not active,\nit won\'t show up in listings, and new data sharing authorizations cannot occur.\nProjects which are "active" but not approved may have some information shared\nin an "In Development" section, so Open Humans members can see potential\nupcoming studies.')),
                ('badge_image', models.ImageField(blank=True, help_text="A badge that will be displayed on the user's profile once they've connected your project.", max_length=1024, storage=open_humans.storage.PublicStorage(), upload_to=private_sharing.models.badge_upload_path)),
                ('request_sources_access', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), help_text='List of sources this project is requesting access to on Open Humans.', size=None, verbose_name="Data sources you're requesting access to")),
                ('request_message_permission', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], help_text='Permission to send messages to the member. This does not grant access to their email address.', verbose_name='Are you requesting permission to message users?')),
                ('request_username_access', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], help_text="Access to the member's username. This implicitly enables access to anything the user is publicly sharing on Open Humans. Note that this is potentially sensitive and/or identifying.", verbose_name='Are you requesting Open Humans usernames?')),
                ('approved', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('api_access_secret', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Data request activities',
            },
        ),
        migrations.CreateModel(
            name='DataRequestProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_code', models.CharField(max_length=16)),
                ('message_permission', models.BooleanField()),
                ('username_shared', models.BooleanField()),
                ('sources_shared', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='open_humans.Member')),
            ],
        ),
        migrations.RemoveField(
            model_name='datarequestactivity',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='datarequestactivitymember',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='datarequestactivitymember',
            name='member',
        ),
        migrations.RemoveField(
            model_name='oauth2datarequestactivity',
            name='application',
        ),
        migrations.RemoveField(
            model_name='oauth2datarequestactivity',
            name='datarequestactivity_ptr',
        ),
        migrations.RemoveField(
            model_name='onsitedatarequestactivity',
            name='datarequestactivity_ptr',
        ),
        migrations.CreateModel(
            name='OAuth2DataRequestProject',
            fields=[
                ('datarequestproject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='private_sharing.DataRequestProject')),
                ('enrollment_url', models.URLField(help_text="The URL we direct members to if they're interested in sharing data with your project.", verbose_name='Enrollment URL')),
                ('redirect_url', models.URLField(help_text='The return URL for our "authorization code" OAuth2 grant process. You can <a target="_blank" href="">read more about OAuth2 "authorization code" transactions here</a>.', verbose_name='Redirect URL')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
            ],
            options={
                'verbose_name': 'OAuth2 data request project',
            },
            bases=('private_sharing.datarequestproject',),
        ),
        migrations.CreateModel(
            name='OnSiteDataRequestProject',
            fields=[
                ('datarequestproject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='private_sharing.DataRequestProject')),
                ('consent_text', models.TextField(help_text='The "informed consent" text that describes your project to Open Humans members.')),
                ('post_sharing_url', models.URLField(help_text='If provided, after authorizing sharing the\nmember will be taken to this URL. If this URL includes "OH_USER_ID_CODE" within\nit, we will replace that with the member\'s project-specific user_id_code. This\nallows you to direct them to an external survey you operate (e.g. using Google\nForms) where a pre-filled user_id_code field allows you to connect those\nresponses to corresponding data in Open Humans.', verbose_name='Post-sharing URL')),
            ],
            options={
                'verbose_name': 'On-site data request project',
            },
            bases=('private_sharing.datarequestproject',),
        ),
        migrations.DeleteModel(
            name='DataRequestActivity',
        ),
        migrations.DeleteModel(
            name='DataRequestActivityMember',
        ),
        migrations.DeleteModel(
            name='OAuth2DataRequestActivity',
        ),
        migrations.DeleteModel(
            name='OnSiteDataRequestActivity',
        ),
        migrations.AddField(
            model_name='datarequestprojectmember',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='private_sharing.DataRequestProject'),
        ),
        migrations.AddField(
            model_name='datarequestproject',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='open_humans.Member'),
        ),
    ]
