# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0008_auto_20160225_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequestproject',
            name='long_description',
            field=models.TextField(max_length=1000, verbose_name='A long description (1000 characters max)'),
        ),
        migrations.AlterField(
            model_name='datarequestproject',
            name='short_description',
            field=models.CharField(max_length=140, verbose_name='A short description (140 characters max)'),
        ),
        migrations.AlterField(
            model_name='datarequestprojectmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_humans.Member'),
        ),
        migrations.AlterField(
            model_name='datarequestprojectmember',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private_sharing.DataRequestProject'),
        ),
        migrations.AlterField(
            model_name='datarequestprojectmember',
            name='user_id_code',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
