# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-03-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0008_featuredproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequestproject',
            name='all_sources_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datarequestprojectmember',
            name='all_sources_shared',
            field=models.BooleanField(default=False),
        ),
    ]
