# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0009_auto_20160225_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onsitedatarequestproject',
            name='post_sharing_url',
            field=models.URLField(blank=True, help_text='If provided, after authorizing sharing the\nmember will be taken to this URL. If this URL includes "OH_USER_ID_CODE" within\nit, we will replace that with the member\'s project-specific user_id_code. This\nallows you to direct them to an external survey you operate (e.g. using Google\nForms) where a pre-filled user_id_code field allows you to connect those\nresponses to corresponding data in Open Humans.', verbose_name='Post-sharing URL'),
        ),
    ]
