# Generated by Django 2.0.7 on 2018-08-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0009_auto_20180317_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequestprojectmember',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
