# Generated by Django 2.1.1 on 2018-09-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0010_datarequestprojectmember_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequestproject',
            name='deauth_email_notification',
            field=models.BooleanField(default=True, help_text='Receive emails when a member deauthorizes your project', verbose_name='Deauthorize email notifications'),
        ),
        migrations.AddField(
            model_name='datarequestproject',
            name='erasure_supported',
            field=models.BooleanField(default=True, help_text="Whether your project supports erasing a member's data on request"),
        ),
        migrations.AddField(
            model_name='datarequestprojectmember',
            name='erasure_requested',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
