# Generated by Django 2.1.1 on 2018-09-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0010_datarequestprojectmember_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequestproject',
            name='deauth_email_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datarequestproject',
            name='erasure_supported',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datarequestprojectmember',
            name='erasure_requested',
            field=models.BooleanField(default=False),
        ),
    ]
