# Generated by Django 2.1.1 on 2018-09-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0010_datarequestprojectmember_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequestproject',
            name='deauth_email_notification',
            field=models.BooleanField(default=False, help_text='Receive emails when a member deauthorizes your project', verbose_name='Deauthorize email notifications'),
        ),
        migrations.AddField(
            model_name='datarequestproject',
            name='erasure_supported',
            field=models.BooleanField(default=False, help_text="Whether your project supports erasing a member's data on request"),
        ),
        migrations.AddField(
            model_name='datarequestprojectmember',
            name='erasure_requested',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='oauth2datarequestproject',
            name='deauth_webhook',
            field=models.CharField(blank=True, default='', help_text="The URL to send a POST to when a member\n                     requests data erasure.  This request will be in the form\n                     of JSON,\n                     { 'project_member_id': '12345678', 'erasure_requested': True}", max_length=256, verbose_name='Deauthorization Webhook URL'),
        ),
    ]
