# Generated by Django 2.1.3 on 2019-01-11 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0011_auto_20180912_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequestproject',
            name='approval_change_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
