# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0011_auto_20160226_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datarequestprojectmember',
            old_name='user_id_code',
            new_name='project_member_code',
        ),
        migrations.AlterField(
            model_name='onsitedatarequestproject',
            name='post_sharing_url',
            field=models.URLField(blank=True, help_text='If provided, after authorizing sharing the\nmember will be taken to this URL. If this URL includes "OH_PROJECT_MEMBER_CODE"\nwithin it, we will replace that with the member\'s project-specific\nproject_member_code. This allows you to direct them to an external survey you\noperate (e.g. using Google Forms) where a pre-filled project_member_code\nfield allows you to connect those responses to corresponding data in Open\nHumans.', verbose_name='Post-sharing URL'),
        ),
    ]
