# Generated by Django 2.1.3 on 2019-01-11 20:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0011_auto_20180912_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequestproject',
            name='approval_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=2), default=list, editable=False, size=None),
        ),
    ]
