# Generated by Django 2.1.3 on 2019-01-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0011_auto_20180912_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequestproject',
            name='no_public_data',
            field=models.BooleanField(default=False),
        ),
    ]
