# Generated by Django 2.1.1 on 2018-09-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0011_auto_20180911_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2datarequestproject',
            name='deauth_webhook',
            field=models.CharField(blank=True, default='', help_text="The URL to send a POST to when a member\n                     requests data erasure.  This request will be in the form\n                     of JSON,\n                     { 'project_member_id': '12345678', 'erasure_requested': True}", max_length=256, verbose_name='Deauthorization Webhook URL'),
        ),
    ]
