# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0012_auto_20160302_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequestproject',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='"Active" status is required to perform authorization\nprocesses, including during drafting stage. If a project is not active, it\nwon\'t show up in listings, and new data sharing authorizations cannot occur.\nProjects which are "active" but not approved may have some information shared\nin an "In Development" section, so Open Humans members can see potential\nupcoming studies.'),
        ),
        migrations.AlterField(
            model_name='onsitedatarequestproject',
            name='post_sharing_url',
            field=models.URLField(blank=True, help_text='If provided, after authorizing sharing the\nmember will be taken to this URL. If this URL includes "OH_PROJECT_MEMBER_CODE"\nwithin it, we will replace that with the member\'s project-specific\nproject_member_code. This allows you to direct them to an external survey you\noperate (e.g. using Google Forms) where a pre-filled project_member_code field\nallows you to connect those responses to corresponding data in Open Humans.', verbose_name='Post-sharing URL'),
        ),
    ]
