# Generated by Django 2.1.3 on 2019-01-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0013_auto_20190121_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequestproject',
            name='no_public_data',
            field=models.BooleanField(default=False),
        ),
    ]
