# Generated by Django 2.1.5 on 2019-01-24 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0014_datarequestproject_no_public_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequestprojectmember',
            name='last_authorized',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='datarequestprojectmember',
            name='last_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
