# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 05:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0014_auto_20160304_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequestprojectmember',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 4, 5, 14, 50, 931889, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
