# Generated by Django 2.1.5 on 2019-01-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0014_datarequestproject_no_public_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datarequestproject',
            name='request_message_permission',
        ),
        migrations.RemoveField(
            model_name='datarequestprojectmember',
            name='message_permission',
        ),
    ]
