# Generated by Django 2.1.5 on 2019-02-07 19:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0016_auto_20190128_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequestproject',
            name='requested_sources',
            field=models.ManyToManyField(related_name='_datarequestproject_requested_sources_+', to='private_sharing.DataRequestProject'),
        ),
        migrations.AddField(
            model_name='datarequestprojectmember',
            name='granted_sources',
            field=models.ManyToManyField(to='private_sharing.DataRequestProject'),
        ),
        migrations.AlterField(
            model_name='datarequestproject',
            name='request_sources_access',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='List of sources this project is requesting access to on Open Humans.', size=None),
        ),
    ]
