# Generated by Django 2.1.5 on 2019-02-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0017_auto_20190212_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2datarequestproject',
            name='terms_url',
            field=models.URLField(default='', help_text='The URL for your "terms of use" policy.', verbose_name='Terms of Use URL'),
            preserve_default=False,
        ),
    ]
