# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 23:04
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0017_datarequestproject_slug'),
    ]

    operations = [
        # update to unique=True
        migrations.AlterField(
            model_name='datarequestproject',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name', unique=True),
        ),
    ]
