# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 07:14
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0018_auto_20160307_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequestprojectmember',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='datarequestproject',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
