# Generated by Django 2.1.7 on 2019-02-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0012_ontology'),
        ('private_sharing', '0019_auto_20190214_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOntology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='data_categories', to='data_import.Ontology')),
            ],
        ),
        migrations.AddField(
            model_name='datarequestproject',
            name='data_types',
            field=models.ManyToManyField(related_name='data_types', to='private_sharing.ProjectOntology'),
        ),
    ]
