# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0019_auto_20160308_0714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datarequestproject',
            options={},
        ),
    ]
