# Generated by Django 2.1.3 on 2019-04-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0020_auto_20190222_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2datarequestproject',
            name='log_api_access',
            field=models.BooleanField(default=False),
        ),
    ]
