# Generated by Django 2.1.7 on 2019-02-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0012_ontology'),
        ('private_sharing', '0020_auto_20190220_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdatafile',
            name='categories',
            field=models.ManyToManyField(related_name='datafile_categories', to='data_import.Ontology'),
        ),
    ]
