# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0020_auto_20160310_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequestprojectmember',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
    ]
