# Generated by Django 2.1.7 on 2019-02-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_import", "0012_datatype"),
        ("private_sharing", "0020_auto_20190222_0036"),
    ]

    operations = [
        migrations.AddField(
            model_name="datarequestproject",
            name="datatypes",
            field=models.ManyToManyField(to="data_import.DataType"),
        ),
        migrations.AddField(
            model_name="projectdatafile",
            name="registered_datatypes",
            field=models.ManyToManyField(to="data_import.DataType"),
        ),
    ]
