# Generated by Django 2.1.7 on 2019-03-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("private_sharing", "0021_auto_20190222_1939")]

    operations = [
        migrations.AddField(
            model_name="datarequestproject",
            name="auto_add_datatypes",
            field=models.BooleanField(default=False),
        )
    ]
