# Generated by Django 2.2.1 on 2019-05-07 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("private_sharing", "0021_auto_20190412_1908")]

    operations = [
        migrations.AlterField(
            model_name="projectdatafile",
            name="direct_sharing_project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="private_sharing.DataRequestProject",
            ),
        )
    ]
