# Generated by Django 2.2 on 2019-04-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("private_sharing", "0021_auto_20190412_1908")]

    operations = [
        migrations.AlterField(
            model_name="oauth2datarequestproject",
            name="redirect_url",
            field=models.CharField(
                blank=True,
                help_text='The return URL for our "authorization code" OAuth2 grant\n        process. You can <a target="_blank" href="/direct-sharing/oauth2-setup/#setup-oauth2-authorization">read more about OAuth2\n        "authorization code" transactions here</a>.',
                max_length=256,
                verbose_name="Redirect URL",
            ),
        )
    ]
