# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 00:10
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0021_datarequestprojectmember_authorized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequestproject',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='oauth2datarequestproject',
            name='redirect_url',
            field=models.URLField(help_text='The return URL for our "authorization code" OAuth2 grant\n        process. You can <a target="_blank" href="">read more about OAuth2\n        "authorization code" transactions here</a>.', verbose_name='Redirect URL'),
        ),
    ]
