# Generated by Django 2.2 on 2019-04-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("private_sharing", "0021_auto_20190412_1908")]

    operations = [
        migrations.AddField(
            model_name="oauth2datarequestproject",
            name="diyexperiment",
            field=models.BooleanField(default=False),
        )
    ]
