# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0022_auto_20160315_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequestproject',
            name='is_academic_or_nonprofit',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Is this institution or organization an academic institution or non-profit organization?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datarequestprojectmember',
            name='consent_text',
            field=models.TextField(blank=True),
        ),
    ]
