# Generated by Django 2.2.1 on 2019-05-28 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("open_humans", "0014_member_password_reset_redirect"),
        ("private_sharing", "0022_auto_20190507_1843"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="datarequestprojectmember", unique_together={("member", "project")}
        )
    ]
