# Generated by Django 2.2 on 2019-04-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("private_sharing", "0022_auto_20190419_2009")]

    operations = [
        migrations.AddField(
            model_name="oauth2datarequestproject",
            name="diy_project",
            field=models.BooleanField(default=False),
        )
    ]
