# Generated by Django 2.2.3 on 2019-07-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("private_sharing", "0023_auto_20190528_1826")]

    operations = [
        migrations.AlterField(
            model_name="datarequestproject",
            name="registered_datatypes",
            field=models.ManyToManyField(
                blank=True, related_name="source_projects", to="data_import.DataType"
            ),
        ),
        migrations.AlterField(
            model_name="datarequestproject",
            name="requested_sources",
            field=models.ManyToManyField(
                blank=True,
                related_name="requesting_projects",
                to="private_sharing.DataRequestProject",
            ),
        ),
    ]
