# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 01:09
from __future__ import unicode_literals

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0023_auto_20160315_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datarequestproject',
            name='api_access_secret',
        ),
        migrations.AddField(
            model_name='datarequestproject',
            name='master_access_token',
            field=models.CharField(default=common.utils.generate_id, max_length=64),
        ),
    ]
