# Generated by Django 2.2.3 on 2019-11-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("private_sharing", "0024_auto_20190716_0504")]

    operations = [
        migrations.AddField(
            model_name="datarequestproject",
            name="any_datatypes",
            field=models.BooleanField(default=False),
        )
    ]
