# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0024_auto_20160316_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequestprojectmember',
            name='joined',
            field=models.BooleanField(default=False),
        ),
    ]
