# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0025_datarequestprojectmember_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequestprojectmember',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='private_sharing.DataRequestProject'),
        ),
    ]
