# Generated by Django 2.2.7 on 2019-12-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("private_sharing", "0025_datarequestproject_any_datatypes")]

    operations = [
        migrations.AddField(
            model_name="datarequestproject",
            name="review_url",
            field=models.URLField(
                blank=True, verbose_name="URL for project approval review"
            ),
        ),
        migrations.AlterField(
            model_name="datarequestprojectmember",
            name="granted_sources",
            field=models.ManyToManyField(
                related_name="granted_sources", to="private_sharing.DataRequestProject"
            ),
        ),
    ]
