# Generated by Django 2.2.10 on 2020-07-01 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("private_sharing", "0026_auto_20191202_2105")]

    operations = [
        migrations.AddField(
            model_name="oauth2datarequestproject",
            name="webhook_secret",
            field=models.CharField(
                blank=True,
                help_text="If entered, this string will be used to provide a hash verifying Open Humans as the sender.",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(regex="[\x00-\x7f]*"),
                    django.core.validators.MinLengthValidator(16),
                ],
            ),
        )
    ]
