# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0029_auto_20160622_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequestproject',
            name='returned_data_description',
            field=models.CharField(blank=True, max_length=140, verbose_name="A description of data you plan to upload back to the member's profile (140 characters max)"),
        ),
    ]
