# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0029_auto_20160622_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequestproject',
            name='organization',
            field=models.CharField(blank=True, max_length=100, verbose_name='Organization or institution'),
        ),
    ]
