# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sharing', '0032_auto_20160629_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequestproject',
            name='returned_data_description',
            field=models.CharField(blank=True, help_text="Leave this blank if your project doesn't plan to add or return new data for your members.", max_length=140, verbose_name='Description of data you plan to upload to member  accounts (140 characters max)'),
        ),
    ]
