# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-01 23:18
from __future__ import unicode_literals

import autoslug.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('private_sharing', '0001_squashed_0034_auto_20160727_2138'),
        ('open_humans', '0016_auto_20150410_2301'),
        ('open_humans', '0001_squashed_0016_auto_20150410_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('approved', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('principal_investigator', models.CharField(max_length=128)),
                ('organization', models.CharField(max_length=128)),
                ('is_live', models.BooleanField(default=False)),
                ('website', models.CharField(default='', max_length=128)),
                ('researchers', models.ManyToManyField(to=b'studies.Researcher')),
            ],
        ),
        migrations.CreateModel(
            name='StudyGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('revoked', models.DateTimeField(null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_humans.Member')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.Study')),
            ],
        ),
        migrations.AddField(
            model_name='study',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 5, 25, 22, 13, 52, 981561)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default-slug', editable=False, populate_from=b'title', unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_requests', related_query_name=b'data_request', to='studies.Study')),
                ('source', models.CharField(choices=[(b'american_gut', b'American Gut'), (b'go_viral', b'GoViral'), (b'pgp', b'Harvard Personal Genome Project'), (b'wildlife', b'Wild Life of Our Homes'), (b'data_selfie', b'Data selfie'), (b'runkeeper', b'RunKeeper'), (b'twenty_three_and_me', b'23andMe')], default='', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='studygrant',
            name='data_requests',
            field=models.ManyToManyField(to=b'studies.DataRequest'),
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name_plural': 'studies'},
        ),
        migrations.RenameField(
            model_name='study',
            old_name='description',
            new_name='long_description',
        ),
        migrations.AddField(
            model_name='study',
            name='short_description',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='study',
            name='researchers',
            field=models.ManyToManyField(blank=True, to=b'studies.Researcher'),
        ),
        migrations.AlterField(
            model_name='studygrant',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_grants', to='open_humans.Member'),
        ),
        migrations.AlterField(
            model_name='datarequest',
            name='source',
            field=models.CharField(choices=[(b'american_gut', b'American Gut'), (b'go_viral', b'GoViral'), (b'pgp', b'Harvard Personal Genome Project'), (b'wildlife', b'Wild Life of Our Homes'), (b'data_selfie', b'Data selfie'), (b'runkeeper', b'RunKeeper'), (b'twenty_three_and_me', b'23andMe'), (b'ancestry_dna', b'AncestryDNA')], max_length=32),
        ),
        migrations.AlterField(
            model_name='datarequest',
            name='source',
            field=models.CharField(choices=[(b'twenty_three_and_me', b'23andMe'), (b'american_gut', b'American Gut'), (b'ancestry_dna', b'AncestryDNA'), (b'data_selfie', b'Data selfie'), (b'go_viral', b'GoViral'), (b'pgp', b'Harvard Personal Genome Project'), (b'runkeeper', b'RunKeeper'), (b'wildlife', b'Wild Life of Our Homes')], max_length=32),
        ),
        migrations.AlterField(
            model_name='datarequest',
            name='source',
            field=models.CharField(choices=[(b'twenty_three_and_me', b'23andMe'), (b'american_gut', b'American Gut'), (b'ancestry_dna', b'AncestryDNA'), (b'data_selfie', b'Data selfie'), (b'fitbit', b'Fitbit'), (b'go_viral', b'GoViral'), (b'pgp', b'Harvard Personal Genome Project'), (b'illumina_uyg', b'Illumina Understand Your Genome'), (b'moves', b'Moves'), (b'runkeeper', b'RunKeeper'), (b'wildlife', b'Wild Life of Our Homes'), (b'withings', b'Withings')], max_length=32),
        ),
        migrations.AlterField(
            model_name='datarequest',
            name='source',
            field=models.CharField(choices=[(b'twenty_three_and_me', b'23andMe'), (b'american_gut', b'American Gut'), (b'ancestry_dna', b'AncestryDNA'), (b'data_selfie', b'Data selfie'), (b'fitbit', b'Fitbit'), (b'go_viral', b'GoViral'), (b'pgp', b'Harvard Personal Genome Project'), (b'illumina_uyg', b'Illumina Understand Your Genome'), (b'moves', b'Moves'), (b'runkeeper', b'RunKeeper'), (b'wildlife', b'Wild Life of Our Homes'), (b'withings', b'Withings'), (b'ubiome', b'uBiome')], max_length=32),
        ),
        migrations.RemoveField(
            model_name='datarequest',
            name='study',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='user',
        ),
        migrations.RemoveField(
            model_name='study',
            name='researchers',
        ),
        migrations.RemoveField(
            model_name='studygrant',
            name='data_requests',
        ),
        migrations.RemoveField(
            model_name='studygrant',
            name='member',
        ),
        migrations.RemoveField(
            model_name='studygrant',
            name='study',
        ),
        migrations.DeleteModel(
            name='DataRequest',
        ),
        migrations.DeleteModel(
            name='Researcher',
        ),
        migrations.DeleteModel(
            name='Study',
        ),
        migrations.DeleteModel(
            name='StudyGrant',
        ),
    ]
