# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-01 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = []
