# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0013_remove_datarequest_subtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datarequest',
            name='data_file_model',
        ),
        migrations.AddField(
            model_name='datarequest',
            name='source',
            field=models.CharField(choices=[(b'american_gut', b'American Gut'), (b'go_viral', b'GoViral'), (b'pgp', b'Harvard Personal Genome Project'), (b'wildlife', b'Wild Life of Our Homes'), (b'data_selfie', b'Data selfie'), (b'runkeeper', b'RunKeeper'), (b'twenty_three_and_me', b'23andMe')], default='', max_length=32),
            preserve_default=False,
        ),
    ]
