# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 23:37
from __future__ import unicode_literals

from django.db import migrations


def migrate_keeping_pace(apps, schema_editor):
    DataRequest = apps.get_model('studies', 'DataRequest')

    try:
        keeping_pace = DataRequest.objects.get(study__title='Keeping Pace')

        keeping_pace.source = 'runkeeper'
        keeping_pace.save()
    except DataRequest.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0014_auto_20160210_2328'),
    ]

    operations = [
        migrations.RunPython(migrate_keeping_pace),
    ]
