# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0016_auto_20160223_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequest',
            name='source',
            field=models.CharField(choices=[(b'twenty_three_and_me', b'23andMe'), (b'american_gut', b'American Gut'), (b'ancestry_dna', b'AncestryDNA'), (b'data_selfie', b'Data selfie'), (b'go_viral', b'GoViral'), (b'pgp', b'Harvard Personal Genome Project'), (b'runkeeper', b'RunKeeper'), (b'wildlife', b'Wild Life of Our Homes')], max_length=32),
        ),
    ]
