# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0018_auto_20160302_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequest',
            name='source',
            field=models.CharField(choices=[(b'twenty_three_and_me', b'23andMe'), (b'american_gut', b'American Gut'), (b'ancestry_dna', b'AncestryDNA'), (b'data_selfie', b'Data selfie'), (b'fitbit', b'Fitbit'), (b'go_viral', b'GoViral'), (b'pgp', b'Harvard Personal Genome Project'), (b'illumina_uyg', b'Illumina Understand Your Genome'), (b'moves', b'Moves'), (b'runkeeper', b'RunKeeper'), (b'wildlife', b'Wild Life of Our Homes'), (b'withings', b'Withings'), (b'ubiome', b'uBiome')], max_length=32),
        ),
    ]
