# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0020_auto_20160408_0456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datarequest',
            name='study',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='user',
        ),
        migrations.RemoveField(
            model_name='study',
            name='researchers',
        ),
        migrations.RemoveField(
            model_name='studygrant',
            name='data_requests',
        ),
        migrations.RemoveField(
            model_name='studygrant',
            name='member',
        ),
        migrations.RemoveField(
            model_name='studygrant',
            name='study',
        ),
        migrations.DeleteModel(
            name='DataRequest',
        ),
        migrations.DeleteModel(
            name='Researcher',
        ),
        migrations.DeleteModel(
            name='Study',
        ),
        migrations.DeleteModel(
            name='StudyGrant',
        ),
    ]
