# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-06-14 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0001_squashed_0007_auto_20160212_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
