# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0004_datafile_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='task',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='user_data',
        ),
        migrations.DeleteModel(
            name='DataFile',
        ),
    ]
