# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 07:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0006_auto_20160212_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
