# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-02 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('go_viral', '0002_auto_20160822_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
