# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 04:42
from __future__ import unicode_literals

import json

from django.db import migrations


def migrate_data(apps, schema_editor):
    GoViralId = apps.get_model('go_viral', 'GoViralId')

    for go_viral_id in GoViralId.objects.all():
        user_data = go_viral_id.user_data

        if isinstance(user_data.data, basestring):
            user_data.data = json.loads(user_data.data)

        user_data.data['goViralId'] = go_viral_id.value
        user_data.save()


class Migration(migrations.Migration):

    dependencies = [
        ('go_viral', '0007_datafile_metadata'),
    ]

    operations = [
        migrations.RunPython(migrate_data),
        migrations.RemoveField(
            model_name='goviralid',
            name='user_data',
        ),
        migrations.DeleteModel(
            name='GoViralId',
        ),
    ]
